CREATE DATABASE MVC_project;
USE MVC_project;

CREATE TABLE User (
  UserId INT PRIMARY KEY AUTO_INCREMENT,
  Role ENUM('admin', 'doctor', 'patient') NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  HashPassword VARCHAR(255) NOT NULL,
  FirstName VARCHAR(255),
  LastName VARCHAR(255),
  Phone VARCHAR(20)
);

CREATE TABLE Doctor (
  DoctorId INT PRIMARY KEY AUTO_INCREMENT,
  UserId INT NOT NULL,
  FOREIGN KEY (UserId) REFERENCES User(UserId)
);

CREATE TABLE Patient (
  PatientId INT PRIMARY KEY AUTO_INCREMENT,
  UserId INT NOT NULL,
  FOREIGN KEY (UserId) REFERENCES User(UserId)
);

CREATE TABLE Admin (
  AdminId INT PRIMARY KEY AUTO_INCREMENT,
  UserId INT NOT NULL,
  FOREIGN KEY (UserId) REFERENCES User(UserId)
);

CREATE TABLE Booking (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  PatientId INT NOT NULL,
  DoctorId INT NOT NULL,
  Options ENUM('Tructiep', 'Zalo') NOT NULL,
  StartAt DATETIME NOT NULL,
  EndTimeOption ENUM('0.5', '1', '1.5') NOT NULL,
  FOREIGN KEY (PatientId) REFERENCES Patient(PatientId),
  FOREIGN KEY (DoctorId) REFERENCES Doctor(DoctorId)
);

CREATE TABLE Message (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  SenderId INT NOT NULL,
  ReceiverId INT NOT NULL,
  MessageType VARCHAR(255) NOT NULL,
  FOREIGN KEY (SenderId) REFERENCES User(UserId),
  FOREIGN KEY (ReceiverId) REFERENCES User(UserId)
);